Adds source and sink filtering ability to sapp
facebook/sapp pull request #23
Opened 2021-07-09 07:51 UTC by abishekvashok

Adds ability to filter for issues in sapp with SourceName, SourceKind,
SinkName, and SinkKind options.

Tweaks the React UI to display the options in the FilterForm and
modifies the query that it makes with the backend flask server.

Implements the ability on the backend server to filter for issues based
on the given SinkName, SinkKind, SourceName, and SourceKind
filters/options.

Filtering by SourceName, SourceKind, SinkName, and SinkKind are via
additional graphQL subqueries that are concatenated and grouped just
like how features are filtered.

Modifies the HasAny IssuePredicate to have a single class for features
and the new mentioned options

Modifies tests to confront with the new filtering options.

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>
Fixes: https://github.com/MLH-Fellowship/pyre-check/issues/14

2021-07-09 07:53 UTC, abishekvashok commented
Significant attention has been given to fix tests that were broken by these changes. And I've fixed those tests that were breaking due to these changes.

Working Screenshots:

<img width="1440" alt="Screenshot 2021-07-09 at 12 38 56 PM" src="https://user-images.githubusercontent.com/8947010/125043603-bcbc6680-e0b8-11eb-8877-cb3ffcaee0ea.png">
<img width="1440" alt="Screenshot 2021-07-09 at 12 38 49 PM" src="https://user-images.githubusercontent.com/8947010/125043610-bded9380-e0b8-11eb-84ac-734706129b11.png">
<img width="1440" alt="Screenshot 2021-07-09 at 12 38 38 PM" src="https://user-images.githubusercontent.com/8947010/125043620-c04fed80-e0b8-11eb-9cfe-fc4697dc1b86.png">

2021-07-12 14:01 UTC, r0rshark requested changes
This looks very good, thanks for sharing the pictures as well :)
UI filter section looks like it's starting to get pretty large , do you think we can instead have two sections (collapsible would be awesome) one for sources and one for sinks, each with a "name" and a "kind" input.
Moreover I see some tests failing https://github.com/facebook/sapp/pull/23/checks?check_run_id=3033095757 can we address them :)
Also pyre is showing a couple of type errors in the added code (https://github.com/facebook/sapp/runs/3033104881?check_suite_focus=true):
```
sapp/ui/filter_predicates.py:118:12 Incompatible return type [7]: Expected `List[IssueQueryResult]` but got `List[List[IssueQueryResult]]`.
sapp/ui/schema.py:183:12 Incompatible parameter type [6]: Expected `List[str]` for 4th positional only parameter to call `Filter.from_query` but got `Optional[List[str]]`.
```

2021-07-12 14:05 UTC, abishekvashok commented
> UI filter section looks like it's starting to get pretty large , do you think we can instead have two sections (collapsible would be awesome) one for sources and one for sinks, each with a "name" and a "kind" input.

For sure!

I will implement this and fix tests to get back.

2021-07-12 16:54 UTC, abishekvashok commented
Hey @r0rshark had to use pyre-ignore to fix pyre-check but fixed the tests, and implemented the collapsible

<img width="1440" alt="Screenshot 2021-07-12 at 7 57 06 PM" src="https://user-images.githubusercontent.com/8947010/125326685-f1058080-e35f-11eb-8216-05f310d89252.png">

2021-07-13 01:28 UTC, dkgi commented
Oh nice, any chance we could fix the alignment issue in the UI? I.e. make sure the text inputs line up with the rest of the form?

It'd also be nice if this was visually a bit less heavy. I like the "ghost" version with the transparent background from the docs (https://ant.design/components/collapse/).

2021-07-13 05:07 UTC, abishekvashok commented
Hey @dkgi thanks for the nice suggestions.
I have implemented the changes:
<img width="1440" alt="Screenshot 2021-07-13 at 10 35 57 AM" src="https://user-images.githubusercontent.com/8947010/125393854-555b2b00-e3c6-11eb-9d08-e0f0f7b55d2e.png">

I guess it looks more uniform and minimal now :D

2021-07-14 09:54 UTC, r0rshark commented on sapp/ui/frontend/src/Filter.css
> +
@abishekvashok  Internal formatter complained about this line. Can we delete it please :)

2021-07-14 10:04 UTC, abishekvashok commented
@r0rshark done :)

2021-07-15 16:48 UTC, dkgi commented
That looks very nice! Thank you :)

2021-07-15 19:47 UTC, closed without merging